### ISSUE TITLE
Building in MVN with WSL Fails

### ISSUE THREAD

**Issue by cbobed** [dwslab/jRDF2Vec#32]
Hi, 

I've checked out the master branch, done the mvn clean install and quite a lot problems with Nx parsers have appeared ... to the point that after all the tests, it has broken my console encoding: 

![image](https://user-images.githubusercontent.com/12048843/100598261-c7cb3f00-32fe-11eb-83c2-09d0ee62e416.png)

Which branch or tag should I use? 

Thank you! :)

**Comment by janothan** [comment]
Actually `master` is the way to go for development. If you just want the latest jar, download it from the jars branch: https://github.com/dwslab/jRDF2Vec/tree/jars 

If you do `mvn clean install` you will get many errors because I also implemented error tests (as long as the tests pass everything should be right). Of course, you can also ` mvn clean install -DskipTests=True` if you don't want to run the tests.

I have never seen such encoding errors. Which OS and which console are you using?

**Comment by cbobed** [comment]
Sorry for my late reply, I'm currently working with WSL + Ubuntu 20.04 under Win 10. The terminal is the latest windows terminal.

**Comment by janothan** [comment]
Hi @cbobed, I can reproduce your problem. You can find a quick report below.

What I did:
- I installed WSL (Ubuntu 20.04)
- In WSL, I installed conda and created a python environment with the required python packages.
- I installed the JDK and checked JAVA_HOME.

**Building (mvn clean install)**
- This will fail as you outlined.
- Failure is due to the test execution. Everything will work fine if the option `-DskipTests=True` is chosen. 

**Running the JAR**
![jrdf2vec_on_wsl](https://user-images.githubusercontent.com/5711596/103907899-235cc980-5102-11eb-9606-1b4c1d4c02cb.png)

 In the walks directory, I can find the model and vector.txt file containing the vectors. Everything is fine.

**Intermediate Remarks**
The good thing is that the JAR runs fine on WSL. 

I do not develop in WSL, so I never had this issue. If you are on Windows, I recommend for now to build it in the CMD. I will investigate this issue further.

**Comment by janothan** [comment]
While this issue is still under investigation, an easy workaround for running the tests in WSL is redirecting the output to a file:

`mvn clean install &> log.txt`

**Comment by janothan** [comment]
I fixed the bug.
